apiVersion: v1
kind: Pod
metadata:
  name: block-test
spec:
      containers:
      - image: dangula/rook-integration
        name: block-test1
        imagePullPolicy: IfNotPresent
        env:
        - name: TestName
          value: INSERT_TEST_TYPE
        volumeMounts:
        - name: block-persistent-storage
          mountPath: /tmp/rook1
      volumes:
      - name: block-persistent-storage
        persistentVolumeClaim:
          claimName: block-pv-claim
      restartPolicy: Never
