apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: block-pv-claim
  annotations:
    volume.beta.kubernetes.io/storage-class: rook-block
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1M
