apiVersion: v1
kind: Pod
metadata:
  name: object-test
  namespace: rook
spec:
      containers:
      - image: dangula/rook-integration
        name: object-test1
        imagePullPolicy: IfNotPresent
        env:
        - name: TestName
          value: INSERT_TEST_TYPE
        - name: AWS_ENDPOINT
          value: AWS_ENDPOINT_VALUE
        - name: AWS_KEY
          value: AWS_KEY_VALUE
        - name: AWS_SECRET
          value: AWS_SECRET_VALUE
      restartPolicy: Never
